version: "3.8"
services:
  identity:
    build: ./identity-service
    ports:
      - "8081:8080"

  academic:
    build: ./academic-core-service
    ports:
      - "8082:8080"

  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
